-- DEFINE QUE O BANCO DE DADOS Pessoas SERÁ UTILIZADO
USE Pessoas;
GO

-- BUSCA TODAS AS PESSOAS
SELECT * FROM Pessoas;
GO

-- BUSCA TODAS AS CNHs
SELECT * FROM CNHs;
GO

-- BUSCA TODAS OS TELEFONES
SELECT * FROM Telefones;
GO

-- BUSCA TODAS OS EMAILS
SELECT * FROM Emails;
GO