-- CRIA O BANCO DE DADOS Pessoas
CREATE DATABASE Pessoas;

-- DEFINE QUE O BANCO DE DADOS Pessoas SERÁ UTILIZADO
USE Pessoas;

-- CRIAÇÃO DE TABELAS
CREATE TABLE Pessoas(
	IdPessoa INT IDENTITY PRIMARY KEY
	,Nome VARCHAR (255) NOT NULL
);

CREATE TABLE Telefones(
	IdTelefone INT IDENTITY PRIMARY KEY
	,Descricao VARCHAR (255) NOT NULL
	,IdPessoa INT FOREIGN KEY REFERENCES Pessoas (IdPessoa) NOT NULL
);

CREATE TABLE Emails(
	IdEmail INT IDENTITY PRIMARY KEY
	,Descricao VARCHAR (255) NOT NULL
	,IdPessoa INT FOREIGN KEY REFERENCES Pessoas (IdPessoa) NOT NULL
);

CREATE TABLE CNHs(
	IdCNH INT IDENTITY PRIMARY KEY
	,Descricao VARCHAR (255) NOT NULL
	,IdPessoa INT FOREIGN KEY REFERENCES Pessoas (IdPessoa) NOT NULL
);