-- DEFINE QUE O BANCO DE DADOS Pessoas SERÁ UTILIZADO
USE Pessoas;

-- BUSCA TODAS AS PESSOAS
SELECT * FROM Pessoas;

-- BUSCA TODAS AS CNHs
SELECT * FROM CNHs;

-- BUSCA TODAS OS TELEFONES
SELECT * FROM Telefones;

-- BUSCA TODAS OS EMAILS
SELECT * FROM Emails;